### ISSUE TITLE
Play scala NoClassDefFoundError: play/mvc/Results$Status

### ISSUE THREAD

**Issue by XuNeal** [Atmosphere/atmosphere-play#37]
I use the atmosphere-play for a play-scala project,  when I connect the server use websocket, I get some error like:

```java 
java.lang.NoClassDefFoundError: play/mvc/Results$Status
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:658)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:882)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:805)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:282)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:214)
Caused by: java.lang.ClassNotFoundException: play.mvc.Results$Status
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
```

here is the source:
Chat.scala
```scala
@Singleton
@ManagedService(path = "/chat")
class Chat @Inject() extends AtmosphereController {
  private val logger = LoggerFactory.getLogger("circle")

  @Ready
  def onReady(resource: AtmosphereResource) = {
    logger.info("Browser {} connected.", resource.uuid())

  }

  @Disconnect
  def onDisconnected(event: AtmosphereResourceEvent) = {
    if (event.isCancelled) {
      logger.info("Browser {} unexpectedly disconnected", event.getResource.uuid())
    } else if (event.isClosedByClient) {
      logger.info("Browser {} closed the connection", event.getResource.uuid())
    }
  }

  @org.atmosphere.config.service.Message
  def onMessage(message: String) = {
    logger.info("message {}", message)
  }

}
```

GlobalSetting.scala
```scala
@Singleton
class GlobalSetting @Inject()(appLifecycle: ApplicationLifecycle) {
  AtmosphereCoordinator.instance().discover(classOf[CircleController]).ready()

  appLifecycle.addStopHook { () =>
    AtmosphereCoordinator.instance().shutdown()
    Future.successful(())
  }

}
```

build.sbt
```scala
libraryDependencies ++= Seq(
  jdbc,
  cache,
  ws,
  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.0-RC1" % Test,
  "org.atmosphere" % "atmosphere-play" % "2.2.0",
  "org.atmosphere" % "atmosphere-runtime" % "2.4.3",
  "org.atmosphere" % "atmosphere-guice" % "2.4.2"
)
```

**Comment by stegmann-idnow** [comment]
Should be fixed with #38
